data:
  raw_path: data/raw/customers.csv
  processed_path: data/processed/cleaned_customer_churn_data.csv
  features_path: data/processed/customer_data_new_features.csv

features:
  target_col: churn
  input_features:
    - recency
    - frequency
    - engagement_duration
    - inactivity_streak
    - engagement_per_interaction

training:
  model_type: XGBoost
  random_state: 42

  xgb:  # XGBoost hyperparameters
    n_estimators: 300
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    use_label_encoder: False
    eval_metric: logloss

registry:
  model_name: ChurnPredictionModel
